baseurl = "https://j-chao.github.io/j-chao/"
title = "Justin Chao"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "https-j-chao-github-io-j-chao" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
enableEmoji = true

[Author] # Used in authorbox
    name = "Justin Chao"
    bio = "Justin is an emerging software engineer, who is currently fascinated with understanding how engineering  \
            best practices help speed up development cycles and make developing software an enjoyable experience."
    avatar = "img/avatar.png"

[Params]
    subtitle = "A collection of random thoughts and ideas" # Subtitle of your site. Used in site header
    description = "A place for sharing ideas, or just keeping notes." # Description of your site. Used in meta description
    opengraph = true # Enable OpenGraph if true
    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true # Show authorbox at bottom of pages if true
    post_navigation = true # Show post navigation at bottom of pages if true
    postSections = ["posts"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages
    #dateformat = "2006-01-02" # change the format of dates

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

    # Enable "Social" widget, if any of "social_*" set a value
    # social_facebook = "username"
    # social_twitter = "username"
    social_linkedin = "justinchao"
    social_github = "j-chao"
    # social_email = "justin_chao@utexas.edu"
